### ISSUE TITLE
Transcode

### ISSUE THREAD

**Issue by hegemanjr** [snsparrish/NachaLibPHP#4]
On lines 66 and 86 the condition throws an error because it is blank by default.

I was able to fix this by using isset()

//if(!$paymentinfo['Transcode']){ // replaced with "isset" version, without it, it doesn't work
if(!isset($paymentinfo['Transcode'])){

**Comment by twistedbeholder** [comment]
I have fixed the Transcode issue.  There are corrections to both files.  The original index works.  I included a bit of code that includes the "customer files" so I could run it as a web page.  I have also started work on a for to create the customer files.

 
[nacha.txt](https://github.com/snsparrish/NachaLibPHP/files/767060/nacha.txt)
[companyfile.txt](https://github.com/snsparrish/NachaLibPHP/files/767061/companyfile.txt)
[companyfilecreate.txt](https://github.com/snsparrish/NachaLibPHP/files/767074/companyfilecreate.txt)

**Comment by snsparrish** [comment]
Merged and resolved.  Thanks for the pr
